### PR TITLE
Feature/compile on win

### PR DESCRIPTION
**Pull request by vallant**
Hi,
as you can see i didn't really make any functional changes to the project, i just changed the way it is built a bit (including adding it to the github CI :tada: )
It now doesn't make any assumptions on the system it is built on, since gecode and googletest are now referenced via the submodule. The lib didn't built with the newest gecode 6.2.0, so since the last change in the project was in 2015, i assumed that the version it was designed for is 4.4.0, and it seems to build just fine.
The biggest change that might be breaking, depending on your workflow, is that by default now a **static** library is built, instead of a shared one. This is because i changed the `add_library(dither SHARED)` call to just `add_library(dither)`, this way every consumer has the possibility of deciding which library type is needed (in my specific case i'll consume it as static library).
Also, i've changed the way the tests are run, i personally don't have too much experience with ctest, i found that using a custom target that runs the tests works very well too- but if you'd like i can definitely change it back.
Also, to ensure testing works fine, all files now are placed under `build/bin`, such that the tests will find their required dlls without any hussle.

I hope your OK with these changes, i'm happy to make any changes you request :+1:

### CODE REVIEW

**Comment by jesg** [comment]
@vallant the pull request looks good to me.   i had a minor issue with the minimum cmake version.

**Comment by vallant** [comment]
I chose this version because the `GENERATOR_IS_MULTI_CONFIG` flag was introduced in version 3.9. Is this a problem? There are a couple of ways of work around this if needed!
https://cmake.org/cmake/help/latest/prop_gbl/GENERATOR_IS_MULTI_CONFIG.html

**Comment by jesg** [comment]
@vallant can you try building the project on the minimum version of cmake (3.9) the project supports?  the older releases are published on [github](https://github.com/Kitware/CMake/releases).

the `add_executable` syntax you used is not valid until version `3.11`.  in addition to that i had an issue with the command line arguments which were not valid until version `3.15` (unfortunately i was not able to track down the root cause).

> Is this a problem?

yes.  a user should be able to build the project with the minimum version of cmake the project claims to support.

**Comment by vallant** [comment]
Ah, now i understand- i thought you needed to install a different version of cmake locally. Naturally i'll look into that, probably during the weekend. Just in case- would you have a problem with raising the min. cmake version to 3.15, or would you prefer keeping it low?

**Comment by jesg** [comment]
sounds good

> Just in case- would you have a problem with raising the min. cmake version to 3.15, or would you prefer keeping it low?

i'm ok with raising the minimum camke version to 3.15.

**Comment by vallant** [comment]
I've tried different cmake versions now and found that the project builds fine with cmake >= 3.11.

**Pull request merged**
